// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsnvfjbqxqcbnvxjiced.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zbnZmamJxeHFjYm52eGppY2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwOTU2ODQsImV4cCI6MjA4NjY3MTY4NH0.NVHpda8FeTdrCOc-uLU6lYUoZdoFSEPEsZ2bZChpeYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});